create table MyUser (
	ID int not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1,INCREMENT BY 1),
	NAME varchar(64) not null
);

create table UserToken (
	ID int not null primary key GENERATED BY DEFAULT AS IDENTITY (START WITH 1,INCREMENT BY 1),
	token varchar(36) UNIQUE,
	user_id int,
	name varchar(64), 
	roles varchar(1024),
	created_at date not null,
	revoked boolean default false
);

create index idx_myuser on MyUser (ID);
create index idx_usertoken_token on UserToken (token);
create index idx_usertoken_userid on UserToken (user_id);
